version: '3'
services:
  products-service:
    build:
      context: ./products-service
      dockerfile: Dockerfile.debug
    environment:
      - PORT=3000
      - DISCOUNTS_SERVICE_HOST=discounts-service
      - DISCOUNTS_SERVICE_PORT=3001
    container_name: products-service-debug
    image: products-service-debug:latest
    restart: always
    tty: true
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./protos:/products-service/src/protos
  discounts-service:
    build:
      context: ./discounts-service
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=3001
    container_name: discounts-service-debug
    image: discounts-service-debug:latest
    restart: always
    tty: true
    ports:
      - 3001:3001