version: '3'
services:
  products-service:
    build:
      context: ./products-service
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - DISCOUNTS_SERVICE_HOST=localhost
      - DISCOUNTS_SERVICE_PORT=3001
    container_name: products-service
    image: products-service:latest
    restart: always
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./protos:/products-service/src/protos
  discounts-service:
    build:
      context: ./discounts-service
      dockerfile: Dockerfile
    environment:
      - HOST=localhost
      - PORT=3001
    container_name: discounts-service
    image: discounts-service:latest
    restart: always
    tty: true
    ports:
      - 3001:3001