FROM node:9.5.0-alpine
WORKDIR /products-service
COPY . .
RUN apk add --no-cache --virtual .gyp python make g++
RUN npm install --no-cache
RUN apk del .gyp
CMD ["npm", "run", "debug"]
EXPOSE 3000
EXPOSE 9229