# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discount.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "discount.ByBirthDateRequest" do
    optional :birth_date, :int64, 1
    repeated :products, :message, 2, "discount.Product"
  end
  add_message "discount.DefaultResponse" do
    repeated :products, :message, 1, "discount.Product"
  end
  add_message "discount.Product" do
    optional :id, :string, 1
    optional :price_in_cents, :int32, 2
    optional :title, :string, 3
    optional :description, :string, 4
    optional :discount, :message, 5, "discount.Discount"
  end
  add_message "discount.Discount" do
    optional :pct, :double, 1
    optional :value_in_cents, :int32, 2
  end
end

module Discount
  ByBirthDateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("discount.ByBirthDateRequest").msgclass
  DefaultResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("discount.DefaultResponse").msgclass
  Product = Google::Protobuf::DescriptorPool.generated_pool.lookup("discount.Product").msgclass
  Discount = Google::Protobuf::DescriptorPool.generated_pool.lookup("discount.Discount").msgclass
end
