# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: discount.proto for package 'discount'

require 'grpc'
require 'discount_pb'

module Discount
  module GetService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'discount.GetService'

      rpc :ByBirthDate, ByBirthDateRequest, DefaultResponse
    end

    Stub = Service.rpc_stub_class
  end
end
