# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discount.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "discount.GetRequest" do
    optional :user_id, :string, 1
  end
  add_message "discount.GetResponse" do
    repeated :products, :message, 1, "discount.Product"
  end
  add_message "discount.Product" do
    optional :id, :string, 1
    optional :price_in_cents, :int64, 2
    optional :title, :string, 3
    optional :description, :string, 4
    optional :discount, :message, 5, "discount.Discount"
  end
  add_message "discount.Discount" do
    optional :pct, :float, 1
    optional :value_in_cents, :int64, 2
  end
end

module Discount
  GetRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("discount.GetRequest").msgclass
  GetResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("discount.GetResponse").msgclass
  Product = Google::Protobuf::DescriptorPool.generated_pool.lookup("discount.Product").msgclass
  Discount = Google::Protobuf::DescriptorPool.generated_pool.lookup("discount.Discount").msgclass
end
