# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: discount.proto for package ''

require 'grpc'
require 'discount_pb'

module DiscountService
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'DiscountService'

    rpc :get, DiscountRequest, DiscountResponse
  end

  Stub = Service.rpc_stub_class
end
