# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: discount.proto for package 'discount'

require 'grpc'
require 'discount_pb'

module Discount
  module Service
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'discount.Service'

      rpc :get, GetRequest, GetResponse
    end

    Stub = Service.rpc_stub_class
  end
end
